### ISSUE TITLE
doesn't work when e = zeros(1, 1:t), it should be a line, but instead a patch

### ISSUE THREAD

**Issue by doerlbh** [kakearney/boundedline-pkg#6]

**Comment by kakearney** [comment]
This bug reflects a rendering issue in some versions of Matlab where a zero-width patch is displayed as the convex hull of the patch's line rather than just the line itself.  I had previously added a workaround for this, and then accidentally undid the workaround when I added in various NaN-handling options (the workaround involved adding strategically-placed NaNs to the patch's vertices).

This has been fixed via the latest commit (81eeeec6340b3e66d1f94197c2b4b4ce4f99e418).  Closing the issue for now... please reopen if you still experience this bug with the newest code.

**Comment by doerlbh** [comment]
Thank you, Kelly
